### ISSUE TITLE
Question: JLCPCB

### ISSUE THREAD

**Issue by oke24** [Expatria-Technologies/PicoBOB#1]
Hi , a short question - for SMT Assembly at JLCPCB I need a CPL file. 
I couldn't find this file in the PicoBOB directory structure. It it possible to generate this file and copy into the CAM_OUTPUTS folder ? Thanky you very much !

**Comment by andrewmarles** [comment]
You should use the csv in the pick and place folder.

**Comment by oke24** [comment]
Thanks!
