### ISSUE TITLE
Maximum step rate

### ISSUE THREAD

**Issue by jamesbaber** [Expatria-Technologies/PicoBOB#4]
Hello,

I've purchased a PicoBOB and was hoping to utilise the claimed maximum step rate of 180k steps/sec.
My oscilloscope shows a stable pulse up until around 60 kHz with very narrow gaps between pulses. If I try to continue up to 70 kHz, the pulse gaps disappear and it becomes one solid pulse with a few glitches.

At 60kHz, the gaps are ~490 ns long and exhibit very square edges once passed through the SN74HC245 bus transceivers on the Mach3 BOB. Before the buffer, they have rounder edges and still do not properly form at higher frequencies.
I am trying to jog the board from ioSender 2.0.44.

I've tried the PicoBOB and PicoBOB_G540 boards on the grblHAL Web Builder with the same results.
Can you please let me know what the test conditions were for the 180kHz pulse rate spec?

Thanks!

**Comment by andrewmarles** [comment]
You can try reducing the pulse width in your stepper settings.

**Comment by jamesbaber** [comment]
@andrewmarles

Thank you, I did not expect such granular controls to exist!
This has resolved my issue.
